OPENROUTER_API_KEY = "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"
PEXELS_API_KEY = "9qgh0LfqC9Xtd2680FV7tlGBm5ov4NnhkVi7jtjIlE7SSd5a1ymRYOFG"
GMAIL_ADDRESS = "nitinshukla7955@gmail.com"
GMAIL_APP_PASSWORD = "cmlw bkna meft yyey"
RECIPIENT_EMAIL = "nitinshukla7944@gmail.com"
